/* global React, Icon, Button, Badge, DOCUMENTS */

const TABS = [
  { id: "summary", label: "Summary" },
  { id: "qa", label: "Q&A" },
  { id: "related", label: "Related" },
  { id: "annotations", label: "Annotations" },
  { id: "comments", label: "Comments" },
  { id: "versions", label: "Versions" },
];

function DocumentView({ docId, onBack, onOpenChat }) {
  const doc = DOCUMENTS.find((d) => d.id === docId) || DOCUMENTS[0];
  const [tab, setTab] = React.useState("summary");

  const related = DOCUMENTS.filter((d) => d.id !== doc.id).slice(0, 3);

  return (
    <div className="doc-page" data-screen-label="Document">
      <div className="doc-toolbar">
        <button className="doc-back" onClick={onBack} aria-label="Back to search">
          <Icon name="chevron-left" size={20} />
        </button>
        <div className="doc-title-group">
          <h1 className="doc-title">{doc.title}</h1>
          <div className="doc-meta">
            <span className="source">{doc.source}</span>
            {doc.tags.slice(0, 3).map((t) => (
              <React.Fragment key={t}>
                <span className="dot">·</span>
                <span className="tag">{t}</span>
              </React.Fragment>
            ))}
            <span className="dot">·</span>
            <span>Updated {doc.updatedLabel}</span>
          </div>
        </div>
        <div className="doc-controls">
          <Button variant="secondary" size="sm" onClick={() => onOpenChat?.(doc.id)}>
            <Icon name="messages" size={14} /> Chat about this
          </Button>
          <Button variant="secondary" size="sm">
            <Icon name="download" size={14} /> Download
          </Button>
        </div>
      </div>

      <div className="doc-body">
        <div className="doc-preview-col">
          <article className="doc-paper">
            {doc.body.map((b, i) => {
              if (b.type === "h1") return <h1 key={i}>{b.text}</h1>;
              if (b.type === "h2") return <h2 key={i}>{b.text}</h2>;
              return <p key={i}>{b.text}</p>;
            })}
          </article>
        </div>

        <aside className="doc-insight-col">
          <div className="doc-tabs">
            {TABS.map((t) => (
              <button
                key={t.id}
                className={`doc-tab${tab === t.id ? " active" : ""}`}
                onClick={() => setTab(t.id)}
              >
                {t.label}
              </button>
            ))}
          </div>
          <div className="doc-tab-body">
            {tab === "summary" && (
              <>
                <p className="insight-lead">{doc.summary}</p>
                <div className="insight-section">
                  <h3>Entities</h3>
                  <div className="dot-list">
                    {doc.entities.map((e, i) => (
                      <React.Fragment key={e}>
                        {i > 0 && <span className="sep">·</span>}
                        <span className="item">{e}</span>
                      </React.Fragment>
                    ))}
                  </div>
                </div>
                <div className="insight-section">
                  <h3>Tags</h3>
                  <div className="dot-list">
                    {doc.tags.map((t, i) => (
                      <React.Fragment key={t}>
                        {i > 0 && <span className="sep">·</span>}
                        <span className="item">{t}</span>
                      </React.Fragment>
                    ))}
                  </div>
                </div>
                <p className="generated-by">Generated by mistral:7b-instruct · 2025-05-21 09:14 UTC</p>
              </>
            )}

            {tab === "qa" && (
              <div className="insight-section">
                <h3>Ask anything</h3>
                <p style={{ color: "var(--color-text-secondary)" }}>
                  Type a question and press Ask. Answers are grounded in this document.
                </p>
                <div style={{ display: "flex", gap: 8, marginTop: 12 }}>
                  <input className="text-input" placeholder="What does §3.2 cover?" />
                  <Button size="sm">Ask</Button>
                </div>
              </div>
            )}

            {tab === "related" && (
              <div className="insight-section">
                <h3>Related documents</h3>
                {related.map((r) => (
                  <div key={r.id} style={{ padding: "10px 0", borderBottom: "1px solid var(--color-border)" }}>
                    <div style={{ fontWeight: 600, color: "var(--color-text-primary)", fontSize: 14 }}>{r.title}</div>
                    <div style={{ fontSize: 12, color: "var(--color-text-muted)", marginTop: 4 }}>
                      {r.source} · {r.updatedLabel}
                    </div>
                  </div>
                ))}
              </div>
            )}

            {tab === "annotations" && (
              <div className="insight-section">
                <h3>Annotations</h3>
                <p style={{ color: "var(--color-text-secondary)" }}>No annotations yet.</p>
                <p style={{ color: "var(--color-text-muted)", fontSize: 12, marginTop: 8 }}>
                  Add private notes or share evidence with readers.
                </p>
                <div style={{ marginTop: 12 }}>
                  <textarea
                    className="text-input"
                    style={{ height: 80, padding: 8, resize: "vertical" }}
                    placeholder="Add an annotation…"
                  />
                  <div style={{ display: "flex", gap: 8, justifyContent: "flex-end", marginTop: 8 }}>
                    <label style={{ display: "flex", gap: 6, alignItems: "center", fontSize: 12, color: "var(--color-text-secondary)" }}>
                      <input type="checkbox" defaultChecked /> Private
                    </label>
                    <Button size="sm">Add</Button>
                  </div>
                </div>
              </div>
            )}

            {tab === "comments" && (
              <div className="insight-section">
                <h3>Comments</h3>
                <div style={{ padding: "10px 0", borderBottom: "1px solid var(--color-border)" }}>
                  <div style={{ display: "flex", justifyContent: "space-between", alignItems: "baseline" }}>
                    <span style={{ fontWeight: 600, fontSize: 13 }}>K. Tanaka</span>
                    <span className="meta">2 days ago</span>
                  </div>
                  <p style={{ marginTop: 6 }}>Verified the out-of-hours path with paging — works as written.</p>
                </div>
                <div style={{ marginTop: 12 }}>
                  <textarea
                    className="text-input"
                    style={{ height: 60, padding: 8, resize: "vertical" }}
                    placeholder="Add a comment…"
                  />
                  <div style={{ display: "flex", justifyContent: "flex-end", marginTop: 8 }}>
                    <Button size="sm">Post</Button>
                  </div>
                </div>
              </div>
            )}

            {tab === "versions" && (
              <div className="insight-section">
                <h3>Versions</h3>
                <div style={{ padding: "10px 0", borderBottom: "1px solid var(--color-border)", display: "flex", justifyContent: "space-between", alignItems: "center" }}>
                  <div>
                    <div style={{ fontSize: 14, fontWeight: 500 }}>Version 4 <Badge variant="success">Latest</Badge></div>
                    <div className="meta">Today, 09:14</div>
                  </div>
                </div>
                <div style={{ padding: "10px 0", borderBottom: "1px solid var(--color-border)" }}>
                  <div style={{ fontSize: 14, fontWeight: 500 }}>Version 3</div>
                  <div className="meta">May 15, 2025</div>
                </div>
                <div style={{ padding: "10px 0" }}>
                  <div style={{ fontSize: 14, fontWeight: 500 }}>Version 2</div>
                  <div className="meta">Apr 22, 2025</div>
                </div>
              </div>
            )}
          </div>
        </aside>
      </div>
    </div>
  );
}

window.DocumentView = DocumentView;
