import type { QAResponse } from "@/api/qa";
import { CitationList } from "./CitationList";
import styles from "./AnswerPanel.module.css";

interface AnswerPanelProps {
  result: QAResponse;
  returnPath?: string;
}

export function AnswerPanel({ result, returnPath }: AnswerPanelProps) {
  return (
    <div className={styles.panel}>
      <p className={styles.groundingNote}>
        Based only on documents you have access to.
      </p>
      <div className={styles.answer}>{result.answer}</div>
      <CitationList citations={result.citations} returnPath={returnPath} />
      {result.model && (
        <p className={styles.modelNote}>Generated by {result.model}</p>
      )}
    </div>
  );
}
